"""Constructor configuration contracts and connection-scoped negotiation."""

from __future__ import annotations

import pytest

from mqttnext.api.async_client import AsyncClient
from mqttnext.codec.buffer import DEFAULT_MAX_PACKET_SIZE, IncrementalDecoder
from mqttnext.codec.properties import CONNECT
from mqttnext.codec.vbi import decode_vbi
from mqttnext.enums import MQTTProtocolVersion
from mqttnext.packets import ConnectPacket
from mqttnext.protocol.engine import EngineConfig, ProtocolEngine
from mqttnext.protocol.negotiated import NegotiatedSettings
from mqttnext.protocol.reconnect import ReconnectPolicy
from mqttnext.types import Properties


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("keepalive", -1),
        ("keepalive", 65536),
        ("local_receive_maximum", 0),
        ("local_receive_maximum", 65536),
        ("max_outbound_inflight", 0),
        ("max_queued", -1),
        ("maximum_packet_size", 1),
        ("topic_alias_maximum", -1),
        ("topic_alias_maximum", 65536),
    ],
)
def test_engine_config_rejects_invalid_ranges(field: str, value: int) -> None:
    with pytest.raises(ValueError):
        EngineConfig(**{field: value})


@pytest.mark.parametrize(
    "kwargs",
    [
        {"max_outbound_messages": 0},
        {"max_outbound_bytes": 0},
        {"max_pending_messages": 0},
        {"ack_timeout": 0},
        {"ping_timeout": 0},
        {"client_id": b"bad"},
        {"username": b"bad"},
        {"password": object()},
    ],
)
def test_async_client_rejects_invalid_configuration(kwargs) -> None:
    with pytest.raises(ValueError):
        AsyncClient(**kwargs)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"initial_delay": -1},
        {"multiplier": 0.5},
        {"initial_delay": 2, "max_delay": 1},
        {"max_retries": -1},
        {"stable_after": -1},
        {"connect_timeout": 0},
    ],
)
def test_reconnect_policy_rejects_invalid_configuration(kwargs) -> None:
    with pytest.raises(ValueError):
        ReconnectPolicy(**kwargs)


def test_default_local_packet_limit_is_announced_in_mqtt5_connect() -> None:
    client = AsyncClient(protocol=MQTTProtocolVersion.MQTTv5)
    assert client._decoder.max_packet_size == DEFAULT_MAX_PACKET_SIZE
    assert client._engine.config.maximum_packet_size == DEFAULT_MAX_PACKET_SIZE

    wire = client._engine.begin_connect()
    remaining_length, pos = decode_vbi(wire, 1)
    body = wire[pos : pos + remaining_length]
    # Decode enough of CONNECT to inspect the properties through the packet
    # generated by the engine: the value must be present on the wire.
    assert DEFAULT_MAX_PACKET_SIZE.to_bytes(4, "big") in body


def test_negotiated_capabilities_reset_before_new_connection() -> None:
    engine = ProtocolEngine()
    engine.negotiated = NegotiatedSettings(
        maximum_qos=0,
        retain_available=False,
        maximum_packet_size=128,
    )

    engine.begin_connect()

    assert engine.negotiated.maximum_qos == 2
    assert engine.negotiated.retain_available is True
    assert engine.negotiated.maximum_packet_size is None
